#基础镜像使用java
FROM openjdk:8
#作者
MAINTAINER Hone-tooy-young
#VOLUME指定临时文件目录为/tmp,在主机/var/Lib/docker目录下创建了一个临时文件并链接到容器的/tmp
VOLUME /tmp
#将jar包添加到容器中并更名为dbmovie.jar
ADD DBMovie-0.0.1-SNAPSHOT.jar dbmovie.jar
#运行jar包
RUN bash -c 'touch /dbmovie.jar'
ENTRYPOINT ["java","-jar","/dbmovie.jar"]
#暴露8099端口作为微服务
EXPOSE 8099
