version: '3'
services:
  mobile-web-best-practice: DB-Movie
    container_name: 'db-movie' #容器名称
    image: nginx #指定镜像
    restart: always
    ports:
      - 8099:8099
    volumes:
      #~ ./nginx.conf为宿主机目录, /etc/nginx为容器目录
      - ./nginx.conf:/etc/nginx/nginx.conf #挂载nginx配置
      #~ ./dist 为宿主机 build 后的dist目录, /usr/src/app为容器目录,
      - ./dist:/usr/share/nginx/html/ #挂载项目
    privileged: true
